modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Juuxel/Adorn/issues"

[[mods]]
modId = "adorn"
version = "${version}"
displayName = "Adorn"
description = "Decorate your home!"
authors = "Juuz"
logoFile = "icon.png"

[[mixins]]
config = "mixins.adorn.common.json"

[[mixins]]
config = "mixins.adorn.forge.json"

[[dependencies.adorn]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"

[[dependencies.adorn]]
modId = "neoforge"
type = "required"
versionRange="[21.1.8,)"
